version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    volumes:
      - .:/usr/src/api # named volume
      - /usr/src/api/node_modules # anonymous volume for node_modules only
    command: npm run start
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      DEBUG: nodejs-docker-express:*
